"use client";
import {ChangeEvent,FormEvent,useEffect,useRef,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE||"";
const LOCAL_PREFERENCES_KEY="whiteboard-maker:local-preferences:v1";
type Config={api_key:string;base_url:string;text_model:string;image_model:string;tts_url:string;tts_url_2:string;tts_mode:string;has_api_key?:boolean};
type TimingEntry={label:string;seconds:number;running?:boolean};
type Job={id:string;status:"queued"|"running"|"done"|"error";stage:string;progress:number;client_ip?:string;queue_ahead?:number;created_at?:number;task_name?:string;pen_text?:string;style?:string;stroke_detail?:string;job_type?:string;rerender_of?:string;can_rerender?:boolean;can_retry?:boolean;model_retry_count?:number;manual_retry_count?:number;result_url?:string;error?:string;duration?:number;scenes?:number;boards?:number;total_elapsed?:number;current_elapsed?:number;resume_count?:number;checkpoint?:string;timings?:Record<string,TimingEntry>};
type CharacterReference={id:string;name:string;description:string;files:File[]};
type ServiceHealth={queues:{voice:{concurrency:number;waiting:number;nodes:{index:number;url:string;active:boolean;job_id?:string|null}[]};model:{concurrency:number;waiting:number};render:{concurrency:string;active:number}}};
const defaults:Config={api_key:"",base_url:"https://api.openlux.ai/v1",text_model:"gpt-5",image_model:"gpt-image-2",tts_url:"http://127.0.0.1:7860",tts_url_2:"",tts_mode:"gradio"};
const countScriptUnits=(text:string)=>Math.max(1,(text.match(/[^。！？!?；;\n]+[。！？!?；;]?/g)||[]).filter(item=>item.trim()).length);
const estimateMinutes=(text:string)=>Math.max(1/8,text.trim().length/250);
const estimateSceneCount=(text:string)=>Math.max(1,Math.min(countScriptUnits(text),Math.max(1,Math.floor(estimateMinutes(text)*8))));
const styleOptions=[
 {name:"极简粗线简笔白板风",image:"/styles/minimal-whiteboard.webp",desc:"粗黑线 · 少量配色 · 清爽留白"},
 {name:"极简商务涂鸦风",image:"/styles/business-doodle.webp",desc:"几何图表 · 蓝绿配色 · 专业克制"},
 {name:"暖米黄素描白板风",image:"/styles/warm-pencil.webp",desc:"铅笔排线 · 纸张质感 · 温暖细腻"},
 {name:"粗线扁平国风卡通",image:"/styles/guofeng-flat.webp",desc:"朱红玉绿 · 国风纹样 · 生动平涂"},
 {name:"爆款高热吸睛风",image:"/styles/viral-pop.webp",desc:"高饱和 · 强对比 · 短视频冲击力",badge:"热门"},
 {name:"黑金科技发布会风",image:"/styles/black-gold-tech.webp",desc:"黑金光效 · 科技舞台 · 高级权威"},
 {name:"清新治愈手账风",image:"/styles/healing-journal.webp",desc:"柔和水彩 · 治愈配色 · 生活手账"},
 {name:"复古报纸拼贴风",image:"/styles/retro-collage.webp",desc:"撕纸拼贴 · 半色调 · 编辑视觉"},
 {name:"纸感隐喻拼贴风",image:"/styles/paper-metaphor.png",desc:"手工剪纸 · 观点隐喻 · 高级克制",badge:"新增"},
 {name:"3D黏土趣味风",image:"/styles/clay-3d.webp",desc:"黏土材质 · 玩具比例 · 温暖可爱"},
 {name:"赛博霓虹漫画风",image:"/styles/cyber-neon.webp",desc:"霓虹青紫 · 漫画速度线 · 未来感"},
];
export default function Home(){
 const[pageMode,setPageMode]=useState<"standard"|"custom">("standard");
 const[styleReference,setStyleReference]=useState<File|null>(null);
 const[characters,setCharacters]=useState<CharacterReference[]>([{id:"character-1",name:"人物 1",description:"",files:[]}]);
 const[sharedJob,setSharedJob]=useState<Job|null>(null);
 const[includeKeyText,setIncludeKeyText]=useState(true);
 const[copy,setCopy]=useState("");const[reference,setReference]=useState<File|null>(null);const[style,setStyle]=useState("极简粗线简笔白板风");const[scenesPerImage,setScenesPerImage]=useState(1);const[taskName,setTaskName]=useState("");const[penText,setPenText]=useState("");const[strokeDetail,setStrokeDetail]=useState("detailed");const[includeSubtitles,setIncludeSubtitles]=useState(true);const[preferencesLoaded,setPreferencesLoaded]=useState(false);const[settingsOpen,setSettingsOpen]=useState(false);const[config,setConfig]=useState<Config>(defaults);const[health,setHealth]=useState<ServiceHealth|null>(null);const[job,setJob]=useState<Job|null>(null);const[history,setHistory]=useState<Job[]>([]);const[message,setMessage]=useState("");const[connectionMessage,setConnectionMessage]=useState("");const[connectionOk,setConnectionOk]=useState<boolean|null>(null);const[testing,setTesting]=useState(false);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>{let active=true;let reconnectTimer:ReturnType<typeof setInterval>|null=null;const reconnect=async()=>{try{const r=await fetch(`${API}/api/config`);if(!r.ok)throw new Error();const data=await r.json();if(active){setConfig(data);setMessage(current=>current==="后端尚未启动"?"":current);if(reconnectTimer){clearInterval(reconnectTimer);reconnectTimer=null}}}catch{if(active)setMessage("后端尚未启动")}};reconnect();reconnectTimer=setInterval(reconnect,3000);return()=>{active=false;if(reconnectTimer)clearInterval(reconnectTimer);if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{try{const saved=localStorage.getItem(LOCAL_PREFERENCES_KEY);if(saved){const data=JSON.parse(saved);setPenText(String(data.pen_text||""));setStrokeDetail(["light","standard","detailed","full"].includes(data.stroke_detail)?data.stroke_detail:"detailed");setScenesPerImage(Math.max(1,Math.min(4,Number(data.scenes_per_image)||1)));setIncludeKeyText(data.include_key_text!==false);setIncludeSubtitles(data.include_subtitles!==false);if(styleOptions.some(item=>item.name===data.style))setStyle(data.style);if(data.page_mode==="custom"||data.page_mode==="standard")setPageMode(data.page_mode)}}catch{}finally{setPreferencesLoaded(true)}},[]);
 useEffect(()=>{if(!preferencesLoaded)return;const timeout=setTimeout(()=>{localStorage.setItem(LOCAL_PREFERENCES_KEY,JSON.stringify({pen_text:penText,stroke_detail:strokeDetail,scenes_per_image:scenesPerImage,include_key_text:includeKeyText,include_subtitles:includeSubtitles,style,page_mode:pageMode}))},300);return()=>clearTimeout(timeout)},[penText,strokeDetail,scenesPerImage,includeKeyText,includeSubtitles,style,pageMode,preferencesLoaded]);
 const loadHistory=async()=>{try{const[jobsResponse,healthResponse]=await Promise.all([fetch(`${API}/api/jobs?limit=20`),fetch(`${API}/api/health`)]);if(jobsResponse.ok){const items:Job[]=(await jobsResponse.json()).items||[];setHistory(items);setSharedJob(items.find(item=>item.status==="running")||items.find(item=>item.status==="queued")||null)}if(healthResponse.ok)setHealth(await healthResponse.json())}catch{}};
 const onFile=(e:ChangeEvent<HTMLInputElement>)=>setReference(e.target.files?.[0]||null);
 const updateCharacter=(id:string,patch:Partial<CharacterReference>)=>setCharacters(items=>items.map(item=>item.id===id?{...item,...patch}:item));
 const addCharacter=()=>setCharacters(items=>items.length>=5?items:[...items,{id:`character-${Date.now()}`,name:`人物 ${items.length+1}`,description:"",files:[]}]);
 const removeCharacter=(id:string)=>setCharacters(items=>items.length===1?items:items.filter(item=>item.id!==id));
 useEffect(()=>{loadHistory();const id=setInterval(loadHistory,2000);return()=>clearInterval(id)},[]);
 const poll=(id:string)=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch(`${API}/api/jobs/${id}`);if(!r.ok)return;const next=await r.json();setJob(next);if(["done","error"].includes(next.status)){if(timer.current)clearInterval(timer.current);loadHistory()}},1600)};
 const create=async(e:FormEvent)=>{e.preventDefault();setMessage("");if(!reference)return setMessage("请先上传一段清晰的参考音频");if(copy.trim().length<10)return setMessage("文案至少需要 10 个字");const readyCharacters=characters.filter(item=>item.name.trim()&&item.files.length);if(pageMode==="custom"&&!styleReference)return setMessage("请上传一张画面风格参考图");if(pageMode==="custom"&&!readyCharacters.length)return setMessage("请至少添加一个带参考图片的人物");const body=new FormData();body.append("copy",copy);body.append("style",pageMode==="custom"?"自定义参考":style);body.append("reference_mode",pageMode);body.append("scenes_per_image",String(scenesPerImage));body.append("task_name",taskName);body.append("pen_text",penText);body.append("include_key_text",String(includeKeyText));body.append("stroke_detail",strokeDetail);body.append("include_subtitles",String(includeSubtitles));body.append("reference",reference);if(pageMode==="custom"&&styleReference){body.append("style_reference",styleReference);body.append("character_manifest",JSON.stringify(readyCharacters.map(item=>({name:item.name.trim(),description:item.description.trim(),file_count:item.files.length}))));readyCharacters.forEach(item=>item.files.forEach(file=>body.append("character_references",file)))}setJob({id:"",status:"queued",stage:"正在提交任务",progress:1});try{const r=await fetch(`${API}/api/jobs`,{method:"POST",body});const data=await r.json();if(!r.ok)throw new Error(data.detail||"提交失败");setJob(data);loadHistory();poll(data.id)}catch(err){setJob(null);setMessage(err instanceof Error?err.message:"无法连接后端")}};
 const save=async()=>{try{const r=await fetch(`${API}/api/config`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});if(!r.ok)throw new Error();setConfig(await r.json());setConnectionOk(true);setConnectionMessage("设置已保存在本机")}catch{setConnectionOk(false);setConnectionMessage("保存失败，请检查后端连接")}};
 const test=async()=>{setTesting(true);setConnectionMessage("正在测试 GPT-5、GPT Image 2 和语音服务…");setConnectionOk(null);try{const r=await fetch(`${API}/api/config/test`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});if(!r.ok)throw new Error();const d=await r.json();const ok=Boolean(d.openlux?.ok&&d.image?.ok&&d.tts?.ok);setConnectionOk(ok);setConnectionMessage(`${d.openlux.message}；${d.image.message}；${d.tts.message}`)}catch{setConnectionOk(false);setConnectionMessage("测试失败，请确认后端已经启动")}finally{setTesting(false)}};
 const rerender=async(source:Job)=>{setMessage("");try{const r=await fetch(`${API}/api/jobs/${source.id}/rerender`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_name:taskName,stroke_detail:strokeDetail,pen_text:penText,include_key_text:includeKeyText,include_subtitles:includeSubtitles})});const data=await r.json();if(!r.ok)throw new Error(data.detail||"重新渲染提交失败");setJob(data);loadHistory();poll(data.id)}catch(err){setMessage(err instanceof Error?err.message:"重新渲染失败")}};
 const retryFailed=async(source:Job)=>{setMessage("");try{const r=await fetch(`${API}/api/jobs/${source.id}/retry`,{method:"POST"});const data=await r.json();if(!r.ok)throw new Error(data.detail||"继续任务失败");setJob(data);loadHistory();poll(data.id)}catch(err){setMessage(err instanceof Error?err.message:"继续任务失败")}};
 const shownJob=job||sharedJob;const showingShared=!job&&!!sharedJob;
 return <main className="shell">
  <header className="topbar"><div className="brand"><span className="brandMark"><img src="/brand-mark.png" alt=""/></span><span>有温度出品</span></div><nav className="pageSwitch" aria-label="制作页面"><button type="button" className={pageMode==="standard"?"active":""} onClick={()=>setPageMode("standard")}>标准制作</button><button type="button" className={pageMode==="custom"?"active":""} onClick={()=>setPageMode("custom")}>自定义参考</button></nav><button className="ghost" onClick={()=>setSettingsOpen(!settingsOpen)}>⚙ API 设置</button></header>
  <section className="hero"><p className="eyebrow">{pageMode==="custom"?"参考声音 × 文案 × 自定义视觉":"参考声音 × 一段文案"}</p><h1>{pageMode==="custom"?"让你的画风和人物，贯穿每一幕。":"把你的表达，画成一支会说话的白板视频。"}</h1><p className="subtitle">{pageMode==="custom"?"上传风格参考图与多个人物参考，自动生成角色一致的手绘视频。":"克隆参考音色，自动拆分分镜、生成插画、绘制笔迹并合成视频。"}</p></section>
  {settingsOpen&&<section className="settings panel"><Title n="01" title="连接服务" note="密钥仅保存在本机后端"/><div className="settingsGrid">
   <label>OpenLux API Key<input type="password" placeholder={config.has_api_key?"已保存，留空则不修改":"OpenLux API Key"} value={config.api_key.includes("••••")?"":config.api_key} onChange={e=>setConfig({...config,api_key:e.target.value})}/></label>
   <label>OpenLux 接口地址<input value={config.base_url} onChange={e=>setConfig({...config,base_url:e.target.value})}/></label><label>文本模型<input placeholder="gpt-5" value={config.text_model} onChange={e=>setConfig({...config,text_model:e.target.value})}/></label><label>图片模型<input placeholder="gpt-image-2" value={config.image_model} onChange={e=>setConfig({...config,image_model:e.target.value})}/></label><label>语音节点 1<input value={config.tts_url} onChange={e=>setConfig({...config,tts_url:e.target.value})}/></label><label>语音节点 2<input value={config.tts_url_2} onChange={e=>setConfig({...config,tts_url_2:e.target.value})} placeholder="可留空，仅使用一个节点"/></label><label>语音接口类型<select value={config.tts_mode} onChange={e=>setConfig({...config,tts_mode:e.target.value})}><option value="gradio">IndexTTS Gradio（7860）</option><option value="fastapi">IndexTTS API（8000）</option></select></label>
  </div>{health&&<div className="serviceSummary"><strong>局域网共享队列</strong><span>语音 {health.queues.voice.concurrency} 路 · 模型 {health.queues.model.concurrency} 路 · 本地渲染 · 任务断点自动保存</span><div>{health.queues.voice.nodes.map(node=><i key={node.index} className={node.active?"busy":"idle"}>节点 {node.index} · {node.active?"工作中":"空闲"}</i>)}</div></div>}<div className="actions"><button className="secondary" onClick={test} disabled={testing}>{testing?"测试中…":"测试连接"}</button><button className="primary small" onClick={save}>保存设置</button></div>{connectionMessage&&<p className={`message connectionMessage ${connectionOk===true?"success":connectionOk===false?"error":""}`}>{connectionMessage}</p>}</section>}
  <form className="workspace" onSubmit={create}><section className="panel inputPanel"><Title n="01" title="提供素材" note="两项就够了"/>
   <label className={`dropzone ${reference?"ready":""}`}><input type="file" accept="audio/*,.wav,.mp3,.m4a" onChange={onFile}/><span className="uploadIcon">⌁</span><strong>{reference?reference.name:"上传参考音频"}</strong><small>{reference?`${(reference.size/1024/1024).toFixed(1)} MB · 可以开始克隆`:"建议 10–30 秒，单人、无噪声、WAV 最佳"}</small></label>
   <label className="copyLabel"><span>视频文案</span><em>{copy.length} 字</em></label><textarea value={copy} onChange={e=>setCopy(e.target.value)} placeholder="粘贴你想讲的内容。系统会按口播节奏自动拆分场景……"/>
   {pageMode==="standard"?<><div className="styleHeading"><strong>画面风格</strong><span>点击预览图选择，生成结果会严格遵循对应视觉配方</span></div><div className="stylePicker">{styleOptions.map(item=><button type="button" key={item.name} className={`styleCard ${item.badge?"featured":""} ${style===item.name?"selected":""}`} onClick={()=>setStyle(item.name)} aria-pressed={style===item.name}><span className="stylePreview"><img src={item.image} alt={`${item.name}预览`}/>{item.badge&&<em>{item.badge}</em>}<i>{style===item.name?"✓ 已选择":"选择"}</i></span><strong>{item.name}</strong><small>{item.desc}</small></button>)}</div></>:<section className="referenceBuilder"><div className="styleHeading"><strong>自定义参考</strong><span>风格图控制画风，人物组控制角色一致性</span></div><label className={`visualDrop ${styleReference?"ready":""}`}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setStyleReference(e.target.files?.[0]||null)}/><span>风格参考图</span><strong>{styleReference?styleReference.name:"点击上传一张风格图"}</strong><small>只参考配色、线条、材质与构图，不复制其中人物</small></label><div className="characterHeading"><div><strong>人物参考</strong><span>每个人物可上传 1–3 张不同角度图片</span></div><button type="button" onClick={addCharacter} disabled={characters.length>=5}>＋ 添加人物</button></div><div className="characterList">{characters.map((item,index)=><article className="characterCard" key={item.id}><div className="characterTop"><b>人物 {index+1}</b><button type="button" onClick={()=>removeCharacter(item.id)} disabled={characters.length===1}>删除</button></div><div className="characterFields"><label>人物名称<input maxLength={20} value={item.name} onChange={e=>updateCharacter(item.id,{name:e.target.value})} placeholder="例如：小昌"/></label><label>身份或外观说明<input maxLength={80} value={item.description} onChange={e=>updateCharacter(item.id,{description:e.target.value})} placeholder="例如：短发青年，黑色外套"/></label></div><label className={`characterUpload ${item.files.length?"ready":""}`}><input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>updateCharacter(item.id,{files:Array.from(e.target.files||[]).slice(0,3)})}/><strong>{item.files.length?`已选择 ${item.files.length} 张参考图`:"上传人物参考图"}</strong><small>{item.files.length?item.files.map(file=>file.name).join("、"):"推荐正面、侧面、全身照，最多 3 张"}</small></label></article>)}</div><p className="referenceTip">最多添加 5 个人物。系统会按人物名称与文案关系，决定每个分镜出现谁。</p></section>}
  </section>
  <div className="rightStack">
   <section className="panel controlPanel">
    <div className="controlCaption"><strong>成片设置</strong><span>仅保存在当前电脑浏览器</span></div>
    <label className="taskNameField">任务名<input maxLength={30} value={taskName} onChange={e=>setTaskName(e.target.value)} placeholder="留空则自动使用文案前 15 个字"/><small>历史记录显示：{taskName.trim()||copy.replace(/\s+/g,"").slice(0,15)||"等待输入文案"}</small></label>
    <div className="styleRow"><label>每张图包含几个分镜<select value={scenesPerImage} onChange={e=>setScenesPerImage(Number(e.target.value))}><option value={1}>1 个分镜（画面最大）</option><option value={2}>2 个分镜（推荐）</option><option value={3}>3 个分镜</option><option value={4}>4 个分镜（最省图片）</option></select></label><label>笔身文字 / 媒体账号名<input maxLength={12} value={penText} onChange={e=>setPenText(e.target.value)} placeholder="例如：你的账号名"/></label><div className="estimate"><span>文案结构 · 图片上限</span><strong>约 {Math.max(1,Math.round(estimateMinutes(copy)))} 分钟 · 最多 {Math.ceil(estimateSceneCount(copy)/scenesPerImage)} 张</strong></div></div>
    <label className="subtitleToggle"><input type="checkbox" checked={includeKeyText} onChange={e=>setIncludeKeyText(e.target.checked)}/><span><strong>画面重点文字</strong><small>{includeKeyText?"每个分镜显示一条重点短语":"只保留插画，不添加重点词"}</small></span></label>
    <label className="subtitleToggle"><input type="checkbox" checked={includeSubtitles} onChange={e=>setIncludeSubtitles(e.target.checked)}/><span><strong>生成字幕</strong><small>{includeSubtitles?"成片会烧录中文字幕":"只保留画面和配音"}</small></span></label>
    <div className="renderSetting compact"><div><strong>线条绘制量</strong><span>越多越完整，画手动作也越密集</span></div><select value={strokeDetail} onChange={e=>setStrokeDetail(e.target.value)}><option value="light">精简 · 24 条</option><option value="standard">标准 · 48 条</option><option value="detailed">丰富 · 96 条（推荐）</option><option value="full">完整 · 全部线条</option></select></div>
    <button className="primary create" disabled={!!job&&!["done","error"].includes(job.status)}>{job&&!["done","error"].includes(job.status)?"正在制作…":"开始生成视频 →"}</button>{message&&<p className="message">{message}</p>}
   </section>
   <aside className="panel resultPanel"><Title n="02" title="制作进度" note="自动完成全部步骤"/>{!shownJob?<div className="emptyState"><div className="paper"><i/><i/><i/></div><h3>视频将在这里出现</h3><p>上传声音与文案，然后点击开始生成。</p></div>:<div className="jobState">{showingShared&&<p className="sharedTask"><span>局域网共享任务</span><strong>{shownJob.client_ip||"未知 IP"}</strong></p>}<div className={`statusOrb ${shownJob.status}`}><span>{shownJob.status==="done"?"✓":shownJob.status==="error"?"!":"✦"}</span></div><h3>{shownJob.stage}</h3><div className="progress"><i style={{width:`${shownJob.progress}%`}}/></div><p>{shownJob.progress}%{shownJob.scenes?` · ${shownJob.scenes} 幕${shownJob.boards?` / ${shownJob.boards} 张图`:""} · ${shownJob.duration?.toFixed(1)} 秒`:""}</p><div className="timingPanel"><div className="timingTotal"><span>总耗时</span><strong>{formatDuration(shownJob.total_elapsed||0)}</strong>{shownJob.status==="running"&&<em>当前环节 {formatDuration(shownJob.current_elapsed||0)}</em>}</div>{shownJob.timings&&Object.entries(shownJob.timings).map(([key,item])=><div className={`timingRow ${item.running?"running":""}`} key={key}><span>{item.running?"● ":"✓ "}{item.label}</span><strong>{formatDuration(item.seconds)}</strong></div>)}</div>{shownJob.error&&<pre>{shownJob.error}</pre>}{shownJob.status==="error"&&shownJob.can_retry&&<button type="button" className="retryButton" onClick={()=>retryFailed(shownJob)}>重试并继续任务</button>}{shownJob.status==="done"&&shownJob.result_url&&<><video controls src={`${API}${shownJob.result_url}`}/><a className="download" href={`${API}${shownJob.result_url}`}>下载 MP4</a></>}</div>}<ol className="steps"><li>克隆参考音色</li><li>拆分文案分镜</li><li>生成统一插画</li><li>绘制白板动画</li><li>合成音画成片</li></ol></aside>
  </div>
 </form>
  <section className="panel historyPanel"><Title n="03" title="生成历史" note="任务名与笔身文字一目了然"/>{history.length?<div className="historyList">{history.map(item=><article key={item.id}><div><strong><em>{item.job_type==="rerender"?"重新渲染":"视频生成"}</em>{item.task_name||`未命名任务-${item.id.slice(-4)}`}</strong><span>笔身：{item.pen_text||"未设置"} · {formatDate(item.created_at)} · {strokeLabel(item.stroke_detail)} · {item.stage}</span></div><div>{item.status==="done"&&item.result_url&&<a href={`${API}${item.result_url}`}>下载</a>}{item.status==="error"&&item.can_retry&&<button type="button" className="retryHistory" onClick={()=>retryFailed(item)}>从断点继续</button>}{item.can_rerender&&<button type="button" onClick={()=>rerender(item)}>按当前设置重新渲染</button>}</div></article>)}</div>:<p className="historyEmpty">完成一次视频制作后，记录会显示在这里。</p>}</section>
  <footer><span>所有素材与历史记录保存在你的电脑上</span><span>IndexTTS 2.5 · GPT-5 · GPT Image 2 · FFmpeg</span></footer>
 </main>}
function Title({n,title,note}:{n:string;title:string;note:string}){return <div className="sectionTitle"><div><span>{n}</span><h2>{title}</h2></div><p>{note}</p></div>}
function formatDuration(value:number){const seconds=Math.max(0,Math.floor(value));const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);const s=seconds%60;return h?`${h}时 ${m}分 ${s}秒`:m?`${m}分 ${s}秒`:`${s}秒`}
function formatDate(value?:number){return value?new Date(value*1000).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"刚刚"}
function strokeLabel(value?:string){return({light:"精简线条",standard:"标准线条",detailed:"丰富线条",full:"完整线条"} as Record<string,string>)[value||""]||"丰富线条"}
