"use client";
import {ChangeEvent,FormEvent,useEffect,useRef,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE||"";
type Config={api_key:string;base_url:string;text_model:string;image_model:string;tts_url:string;tts_mode:string;has_api_key?:boolean};
type TimingEntry={label:string;seconds:number;running?:boolean};
type Job={id:string;status:"queued"|"running"|"done"|"error";stage:string;progress:number;result_url?:string;error?:string;duration?:number;scenes?:number;boards?:number;total_elapsed?:number;current_elapsed?:number;timings?:Record<string,TimingEntry>};
const defaults:Config={api_key:"",base_url:"https://api.openlux.ai/v1",text_model:"gpt-5",image_model:"gpt-image-2",tts_url:"http://127.0.0.1:7860",tts_mode:"gradio"};
const styleOptions=[
 {name:"极简粗线简笔白板风",image:"/styles/minimal-whiteboard.webp",desc:"粗黑线 · 少量配色 · 清爽留白"},
 {name:"极简商务涂鸦风",image:"/styles/business-doodle.webp",desc:"几何图表 · 蓝绿配色 · 专业克制"},
 {name:"暖米黄素描白板风",image:"/styles/warm-pencil.webp",desc:"铅笔排线 · 纸张质感 · 温暖细腻"},
 {name:"粗线扁平国风卡通",image:"/styles/guofeng-flat.webp",desc:"朱红玉绿 · 国风纹样 · 生动平涂"},
 {name:"爆款高热吸睛风",image:"/styles/viral-pop.webp",desc:"高饱和 · 强对比 · 短视频冲击力",badge:"热门"},
 {name:"黑金科技发布会风",image:"/styles/black-gold-tech.webp",desc:"黑金光效 · 科技舞台 · 高级权威"},
 {name:"清新治愈手账风",image:"/styles/healing-journal.webp",desc:"柔和水彩 · 治愈配色 · 生活手账"},
 {name:"复古报纸拼贴风",image:"/styles/retro-collage.webp",desc:"撕纸拼贴 · 半色调 · 编辑视觉"},
 {name:"3D黏土趣味风",image:"/styles/clay-3d.webp",desc:"黏土材质 · 玩具比例 · 温暖可爱"},
 {name:"赛博霓虹漫画风",image:"/styles/cyber-neon.webp",desc:"霓虹青紫 · 漫画速度线 · 未来感"},
];
export default function Home(){
 const[copy,setCopy]=useState("");const[reference,setReference]=useState<File|null>(null);const[style,setStyle]=useState("极简粗线简笔白板风");const[scenesPerImage,setScenesPerImage]=useState(1);const[penText,setPenText]=useState("");const[includeSubtitles,setIncludeSubtitles]=useState(true);const[preferencesLoaded,setPreferencesLoaded]=useState(false);const[settingsOpen,setSettingsOpen]=useState(false);const[config,setConfig]=useState<Config>(defaults);const[job,setJob]=useState<Job|null>(null);const[message,setMessage]=useState("");const[connectionMessage,setConnectionMessage]=useState("");const[connectionOk,setConnectionOk]=useState<boolean|null>(null);const[testing,setTesting]=useState(false);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>{let active=true;let reconnectTimer:ReturnType<typeof setInterval>|null=null;const reconnect=async()=>{try{const r=await fetch(`${API}/api/config`);if(!r.ok)throw new Error();const data=await r.json();if(active){setConfig(data);setMessage(current=>current==="后端尚未启动"?"":current);if(reconnectTimer){clearInterval(reconnectTimer);reconnectTimer=null}}}catch{if(active)setMessage("后端尚未启动")}};reconnect();reconnectTimer=setInterval(reconnect,3000);return()=>{active=false;if(reconnectTimer)clearInterval(reconnectTimer);if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{let active=true;fetch(`${API}/api/preferences`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active)setPenText(String(data.pen_text||""))}).catch(()=>{}).finally(()=>{if(active)setPreferencesLoaded(true)});return()=>{active=false}},[]);
 useEffect(()=>{if(!preferencesLoaded)return;const timeout=setTimeout(()=>{fetch(`${API}/api/preferences`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pen_text:penText})}).catch(()=>{})},500);return()=>clearTimeout(timeout)},[penText,preferencesLoaded]);
 const onFile=(e:ChangeEvent<HTMLInputElement>)=>setReference(e.target.files?.[0]||null);
 const poll=(id:string)=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch(`${API}/api/jobs/${id}`);if(!r.ok)return;const next=await r.json();setJob(next);if(["done","error"].includes(next.status)&&timer.current)clearInterval(timer.current)},1600)};
 const create=async(e:FormEvent)=>{e.preventDefault();setMessage("");if(!reference)return setMessage("请先上传一段清晰的参考音频");if(copy.trim().length<10)return setMessage("文案至少需要 10 个字");const body=new FormData();body.append("copy",copy);body.append("style",style);body.append("scenes_per_image",String(scenesPerImage));body.append("pen_text",penText);body.append("include_subtitles",String(includeSubtitles));body.append("reference",reference);setJob({id:"",status:"queued",stage:"正在提交任务",progress:1});try{const r=await fetch(`${API}/api/jobs`,{method:"POST",body});const data=await r.json();if(!r.ok)throw new Error(data.detail||"提交失败");setJob(data);poll(data.id)}catch(err){setJob(null);setMessage(err instanceof Error?err.message:"无法连接后端")}};
 const save=async()=>{try{const r=await fetch(`${API}/api/config`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});if(!r.ok)throw new Error();setConfig(await r.json());setConnectionOk(true);setConnectionMessage("设置已保存在本机")}catch{setConnectionOk(false);setConnectionMessage("保存失败，请检查后端连接")}};
 const test=async()=>{setTesting(true);setConnectionMessage("正在测试 GPT-5、GPT Image 2 和语音服务…");setConnectionOk(null);try{const r=await fetch(`${API}/api/config/test`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});if(!r.ok)throw new Error();const d=await r.json();const ok=Boolean(d.openlux?.ok&&d.image?.ok&&d.tts?.ok);setConnectionOk(ok);setConnectionMessage(`${d.openlux.message}；${d.image.message}；${d.tts.message}`)}catch{setConnectionOk(false);setConnectionMessage("测试失败，请确认后端已经启动")}finally{setTesting(false)}};
 return <main className="shell">
  <header className="topbar"><div className="brand"><span className="brandMark"><img src="/brand-mark.png" alt=""/></span><span>有温度出品</span></div><button className="ghost" onClick={()=>setSettingsOpen(!settingsOpen)}>⚙ API 设置</button></header>
  <section className="hero"><p className="eyebrow">参考声音 × 一段文案</p><h1>把你的表达，画成一支会说话的白板视频。</h1><p className="subtitle">克隆参考音色，自动拆分分镜、生成插画、绘制笔迹并合成视频。</p></section>
  {settingsOpen&&<section className="settings panel"><Title n="01" title="连接服务" note="密钥仅保存在本机后端"/><div className="settingsGrid">
   <label>OpenLux API Key<input type="password" placeholder={config.has_api_key?"已保存，留空则不修改":"OpenLux API Key"} value={config.api_key.includes("••••")?"":config.api_key} onChange={e=>setConfig({...config,api_key:e.target.value})}/></label>
   <label>OpenLux 接口地址<input value={config.base_url} onChange={e=>setConfig({...config,base_url:e.target.value})}/></label><label>文本模型<input placeholder="gpt-5" value={config.text_model} onChange={e=>setConfig({...config,text_model:e.target.value})}/></label><label>图片模型<input placeholder="gpt-image-2" value={config.image_model} onChange={e=>setConfig({...config,image_model:e.target.value})}/></label><label>语音服务地址<input value={config.tts_url} onChange={e=>setConfig({...config,tts_url:e.target.value})}/></label><label>语音接口类型<select value={config.tts_mode} onChange={e=>setConfig({...config,tts_mode:e.target.value})}><option value="gradio">IndexTTS Gradio（7860）</option><option value="fastapi">IndexTTS API（8000）</option></select></label>
  </div><div className="actions"><button className="secondary" onClick={test} disabled={testing}>{testing?"测试中…":"测试连接"}</button><button className="primary small" onClick={save}>保存设置</button></div>{connectionMessage&&<p className={`message connectionMessage ${connectionOk===true?"success":connectionOk===false?"error":""}`}>{connectionMessage}</p>}</section>}
  <form className="workspace" onSubmit={create}><section className="panel inputPanel"><Title n="01" title="提供素材" note="两项就够了"/>
   <label className={`dropzone ${reference?"ready":""}`}><input type="file" accept="audio/*,.wav,.mp3,.m4a" onChange={onFile}/><span className="uploadIcon">⌁</span><strong>{reference?reference.name:"上传参考音频"}</strong><small>{reference?`${(reference.size/1024/1024).toFixed(1)} MB · 可以开始克隆`:"建议 10–30 秒，单人、无噪声、WAV 最佳"}</small></label>
   <label className="copyLabel"><span>视频文案</span><em>{copy.length} 字</em></label><textarea value={copy} onChange={e=>setCopy(e.target.value)} placeholder="粘贴你想讲的内容。系统会按口播节奏自动拆分场景……"/>
   <div className="styleHeading"><strong>画面风格</strong><span>点击预览图选择，生成结果会严格遵循对应视觉配方</span></div>
   <div className="stylePicker">{styleOptions.map(item=><button type="button" key={item.name} className={`styleCard ${item.badge?"featured":""} ${style===item.name?"selected":""}`} onClick={()=>setStyle(item.name)} aria-pressed={style===item.name}><span className="stylePreview"><img src={item.image} alt={`${item.name}预览`}/>{item.badge&&<em>{item.badge}</em>}<i>{style===item.name?"✓ 已选择":"选择"}</i></span><strong>{item.name}</strong><small>{item.desc}</small></button>)}</div>
  </section><div className="rightStack"><section className="panel controlPanel"><div className="controlCaption"><strong>成片设置</strong><span>确认后即可开始制作</span></div><div className="styleRow"><label>每张图包含几个分镜<select value={scenesPerImage} onChange={e=>setScenesPerImage(Number(e.target.value))}><option value={1}>1 个分镜（画面最大）</option><option value={2}>2 个分镜（推荐）</option><option value={3}>3 个分镜</option><option value={4}>4 个分镜（最省图片）</option></select></label><label>笔身文字 / 媒体账号名<input maxLength={12} value={penText} onChange={e=>setPenText(e.target.value)} placeholder="例如：你的账号名"/></label><div className="estimate"><span>预计时长 · 图片数</span><strong>约 {Math.max(1,Math.round(copy.length/250))} 分钟 · {Math.ceil(Math.max(3,Math.min(12,Math.round(Math.max(1,copy.length/4)/8)))/scenesPerImage)} 张</strong></div></div><label className="subtitleToggle"><input type="checkbox" checked={includeSubtitles} onChange={e=>setIncludeSubtitles(e.target.checked)}/><span><strong>生成字幕</strong><small>{includeSubtitles?"成片会烧录中文字幕":"只保留画面和配音"}</small></span></label><button className="primary create" disabled={!!job&&!["done","error"].includes(job.status)}>{job&&!["done","error"].includes(job.status)?"正在制作…":"开始生成视频 →"}</button>{message&&<p className="message">{message}</p>}</section><aside className="panel resultPanel"><Title n="02" title="制作进度" note="自动完成全部步骤"/>{!job?<div className="emptyState"><div className="paper"><i/><i/><i/></div><h3>视频将在这里出现</h3><p>上传声音与文案，然后点击开始生成。</p></div>:<div className="jobState"><div className={`statusOrb ${job.status}`}><span>{job.status==="done"?"✓":job.status==="error"?"!":"✦"}</span></div><h3>{job.stage}</h3><div className="progress"><i style={{width:`${job.progress}%`}}/></div><p>{job.progress}%{job.scenes?` · ${job.scenes} 幕${job.boards?` / ${job.boards} 张图`:""} · ${job.duration?.toFixed(1)} 秒`:""}</p><div className="timingPanel"><div className="timingTotal"><span>总耗时</span><strong>{formatDuration(job.total_elapsed||0)}</strong>{job.status==="running"&&<em>当前环节 {formatDuration(job.current_elapsed||0)}</em>}</div>{job.timings&&Object.entries(job.timings).map(([key,item])=><div className={`timingRow ${item.running?"running":""}`} key={key}><span>{item.running?"● ":"✓ "}{item.label}</span><strong>{formatDuration(item.seconds)}</strong></div>)}</div>{job.error&&<pre>{job.error}</pre>}{job.status==="done"&&job.result_url&&<><video controls src={`${API}${job.result_url}`}/><a className="download" href={`${API}${job.result_url}`}>下载 MP4</a></>}</div>}<ol className="steps"><li>克隆参考音色</li><li>拆分文案分镜</li><li>生成统一插画</li><li>绘制白板动画</li><li>合成音画成片</li></ol></aside></div></form>
  <footer><span>所有素材保存在你的电脑上</span><span>IndexTTS 2.5 · GPT-5 · GPT Image 2 · FFmpeg</span></footer>
 </main>}
function Title({n,title,note}:{n:string;title:string;note:string}){return <div className="sectionTitle"><div><span>{n}</span><h2>{title}</h2></div><p>{note}</p></div>}
function formatDuration(value:number){const seconds=Math.max(0,Math.floor(value));const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);const s=seconds%60;return h?`${h}时 ${m}分 ${s}秒`:m?`${m}分 ${s}秒`:`${s}秒`}
